In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('E:\\Downloads\\weather-dataset-rattle-package\\weatherAUS.csv')

df

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN   
1       2008-12-02   Albury      7.4     25.1       0.0          NaN   
2       2008-12-03   Albury     12.9     25.7       0.0          NaN   
3       2008-12-04   Albury      9.2     28.0       0.0          NaN   
4       2008-12-05   Albury     17.5     32.3       1.0          NaN   
5       2008-12-06   Albury     14.6     29.7       0.2          NaN   
6       2008-12-07   Albury     14.3     25.0       0.0          NaN   
7       2008-12-08   Albury      7.7     26.7       0.0          NaN   
8       2008-12-09   Albury      9.7     31.9       0.0          NaN   
9       2008-12-10   Albury     13.1     30.1       1.4          NaN   
10      2008-12-11   Albury     13.4     30.4       0.0          NaN   
11      2008-12-12   Albury     15.9     21.7       2.2          NaN   
12      2008-12-13   Albury     15.9     18.6      15.6          NaN   
13      2008-12-14   Albury     12.6     21.0       3.6          NaN   
14      2008-12-16   Albury      9.8     27.7       NaN          NaN   
15      2008-12-17   Albury     14.1     20.9       0.0          NaN   
16      2008-12-18   Albury     13.5     22.9      16.8          NaN   
17      2008-12-19   Albury     11.2     22.5      10.6          NaN   
18      2008-12-20   Albury      9.8     25.6       0.0          NaN   
19      2008-12-21   Albury     11.5     29.3       0.0          NaN   
20      2008-12-22   Albury     17.1     33.0       0.0          NaN   
21      2008-12-23   Albury     20.5     31.8       0.0          NaN   
22      2008-12-24   Albury     15.3     30.9       0.0          NaN   
23      2008-12-25   Albury     12.6     32.4       0.0          NaN   
24      2008-12-26   Albury     16.2     33.9       0.0          NaN   
25      2008-12-27   Albury     16.9     33.0       0.0          NaN   
26      2008-12-28   Albury     20.1     32.7       0.0          NaN   
27      2008-12-29   Albury     19.7     27.2       0.0          NaN   
28      2008-12-30   Albury     12.5     24.2       1.2          NaN   
29      2008-12-31   Albury     12.0     24.4       0.8          NaN   
...            ...      ...      ...      ...       ...          ...   
142163  2017-05-26    Uluru     14.3     27.6       0.4          NaN   
142164  2017-05-27    Uluru      9.3     28.0       0.0          NaN   
142165  2017-05-28    Uluru      8.0     24.6       0.0          NaN   
142166  2017-05-29    Uluru     12.7     22.2       0.0          NaN   
142167  2017-05-30    Uluru      9.4     22.7       0.0          NaN   
142168  2017-05-31    Uluru      5.4     20.5       0.0          NaN   
142169  2017-06-01    Uluru      5.6     19.4       0.0          NaN   
142170  2017-06-02    Uluru      1.5     19.2       0.0          NaN   
142171  2017-06-03    Uluru      3.8     19.8       0.0          NaN   
142172  2017-06-04    Uluru      4.5     18.8       0.0          NaN   
142173  2017-06-05    Uluru      4.9     20.7       0.0          NaN   
142174  2017-06-06    Uluru      1.2     20.8       0.0          NaN   
142175  2017-06-07    Uluru      0.5     21.7       0.0          NaN   
142176  2017-06-08    Uluru      4.0     20.0       0.0          NaN   
142177  2017-06-09    Uluru      3.4     19.8       0.0          NaN   
142178  2017-06-10    Uluru      3.2     18.6       0.0          NaN   
142179  2017-06-11    Uluru      2.4     19.1       0.0          NaN   
142180  2017-06-12    Uluru      5.1     19.7       0.0          NaN   
142181  2017-06-13    Uluru      2.5     21.2       0.0          NaN   
142182  2017-06-14    Uluru      2.3     21.4       0.0          NaN   
142183  2017-06-15    Uluru      2.6     22.5       0.0          NaN   
142184  2017-06-16    Uluru      5.2     24.3       0.0          NaN   
142185  2017-06-17    Uluru      6.4     23.4       0.0          NaN   
142186  2017-06-18    Uluru      8.0     20.7       0.

In [3]:
df = df.drop(['Date','Location','Evaporation','Sunshine','Cloud9am','Cloud3pm','RISK_MM'],axis=1)

In [4]:
df['RainToday']=df['RainToday'].replace({'No':0,'Yes':1})

df['RainTomorrow'] = df['RainTomorrow'].replace({'No':0,'Yes':1})


In [5]:
df['WindGustDir'] = pd.get_dummies(df['WindGustDir'])

df['WindGustSpeed'] = pd.get_dummies(df['WindGustSpeed'])

df['WindDir9am'] = pd.get_dummies(df['WindDir9am'])

df['WindDir3pm'] = pd.get_dummies(df['WindDir3pm'])

In [6]:
df = df.dropna(how='any')

In [7]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
lben = LabelEncoder()

In [10]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [14]:
from sklearn.ensemble  import BaggingClassifier

In [17]:
from sklearn.tree import DecisionTreeClassifier

In [38]:
dtree = DecisionTreeClassifier(criterion='entropy',max_depth= 5,min_samples_split=2)

dtree_gini = DecisionTreeClassifier(criterion='gini',max_depth=7,min_samples_split=2)
                                   

In [75]:
Bg_classifier_dtree = BaggingClassifier(base_estimator = dtree,n_estimators=10,max_features=10)

In [76]:
Bg_classifier_dtree.fit(x_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=10,
         max_samples=1.0, n_estimators=10, n_jobs=None, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [77]:
y_pred = Bg_classifier_dtree.predict(x_test)

In [78]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [79]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[23497   636]
 [ 4478  2381]]


In [80]:
print(accuracy_score(y_test,y_pred))

0.8349896747547755


In [43]:
Bg_classifier_gini = BaggingClassifier(base_estimator= dtree_gini)

In [62]:
Bg_classifier_gini.fit(x_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=7,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=None, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [63]:
y_pred = Bg_classifier_gini.predict(x_test)

In [65]:
cm_gini = confusion_matrix(y_test,y_pred)
print(cm_gini)

[[23146   987]
 [ 3781  3078]]


In [47]:
import pickle 

In [52]:
with open('model_pickle','wb') as f:
    pickle.dump(Bg_classifier_gini,f)

In [53]:
with open ('model_pickle','rb') as f:
    bg_gn= pickle.load(f)
    

In [56]:
y_pred = bg_gn.predict(x_test)

In [57]:
cm_bg_pickle = confusion_matrix(y_test,y_pred)

In [61]:
print(cm_bg_pickle)

[[23104  1029]
 [ 3771  3088]]


In [82]:
with open('Bg_classifier_dtree','wb') as f:
    pickle.dump(Bg_classifier_dtree,f)
    

In [84]:
with open('Bg_classifier_dtree','rb') as f:
    bg_dtree=pickle.load(f)

In [87]:
y_pred_dtree = bg_dtree.predict(x_test)

In [93]:

cm_dtree_en = confusion_matrix(y_pred_dtree,y_test)
print(cm_dtree_en)

[[23497  4478]
 [  636  2381]]


In [94]:
print(accuracy_score(y_pred_dtree,y_test))

0.8349896747547755
